name: Run Prettier for Teemu 👨
on: push

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prettify code
        uses: creyD/prettier_action@v3.1
        with:
          prettier_options: --write .
          commit_message: '🧹💨 Cleaned up some code'
